version: '3'

networks:
  my_network:

services:
    node:
        build: 
            context: ./
            dockerfile: ./docker/node/Dockerfile
        container_name: node_base
        ports: 
            - 8000:8000
        volumes: 
            - ./:/var/www/html
        networks: 
            - my_network
        tty: true
    mariadb:
        build:
            context: ./
            dockerfile: ./docker/mariadb/Dockerfile
        container_name: mariadb_node_base
        restart: unless-stopped
        tty: true
        ports:
            - "33060:3306"
        volumes:
            - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_DATABASE: node_base
            MYSQL_USER: caerux
            MYSQL_PASSWORD: .caerux
            MYSQL_ROOT_PASSWORD: .caerux
            SERVICE_NAME: mysql
        networks:
            - my_network